### ISSUE TITLE
Differentiate owamp and udp bwctl loss

### ISSUE THREAD

**Issue by sowmyab** [esnet/maddash#16]
A user reported 

"Results from owamp and UDP bwctl loss bleed together in Maddash and Nagios checks. It would be nice if when viewing your owamp data, the results presented were only from owamp tests. Currently if I click a square in my owamp mesh, if there happens to be a UDP bwctl test between the two, I see loss from both owamp and UDP bwctl tests. The Nagios checks are retrieving the same information."

**Comment by arlake228** [comment]
No changes required to MaDDash for this. This was also already fixed in perfsonar/project#1076
