### ISSUE TITLE
Request to see raw packet loss

### ISSUE THREAD

**Issue by sowmyab** [esnet/maddash#17]
A user reported

"It would be very nice to optionally see raw numbers rather than percent or average where possible. Losing 1 out of 250 packets in an owamp test = 0.4%, but that 0.4% isn’t easily understood unless you know there were 250 packets. I would like to see this supported in the Nagios checks as well as Maddash."

**Comment by arlake228** [comment]
No changes required to MaDDash. See perfsonar/nagios#4
