### ISSUE TITLE
Apache locks out proxying to maddash-server

### ISSUE THREAD

**Issue by candlerb** [esnet/maddash#21]
If maddash-server goes down for a short time (e.g. while it is being restarted), and in the mean time Apache tries to proxy to it, it marks the server as down and will no longer proxy to it.

~~~
tail /var/log/httpd/error_log
...
[Tue Sep 08 16:38:35 2015] [error] (111)Connection refused: proxy: HTTP: attempt to connect to 127.0.0.1:8881 (localhost) failed
[Tue Sep 08 16:38:35 2015] [error] ap_proxy_connect_backend disabling worker for (localhost)
[Tue Sep 08 16:38:35 2015] [error] proxy: HTTP: disabled connection for (localhost)
[Tue Sep 08 16:39:24 2015] [error] proxy: HTTP: disabled connection for (localhost)
[Tue Sep 08 16:39:24 2015] [error] proxy: HTTP: disabled connection for (localhost)
~~~

Although restarting Apache fixes this, it's only temporary until the next occurrence.

But there is a simple fix, which is to add `status=+I` (letter 'i') to the ProxyPass line in `/etc/httpd/conf.d/apache-maddash.conf`

~~~
    ProxyPass /maddash http://localhost:8881/maddash status=+I
~~~

**Comment by soichih** [comment]
I recommend switching to nginx as a web proxy. It's much easier to configure and reliable than apache, and it's faster than mod_proxy.

**Comment by candlerb** [comment]
Apache is fine for this application, it just needs to be configured properly.
