### ISSUE TITLE
Hostname labels on status matrix get chopped off if they are too long

### ISSUE THREAD

**Issue by soichih** [esnet/maddash#22]
I was asked to submit this issue for a user from OpenScienceGrid. Please let me know if this is not a good place to submit these types of request.

Currently, maddash status matrix display trims the left end of a long hostname. We've made an effort to shorten the hostname to work around this problem by adjusting the name generated by MyOSG generated meshconfig, but it looks like this is still an issue.

For example

> http://psmad.grid.iu.edu/maddash-webui/index.cgi?dashboard=Dual-Stack%20Mesh%20Config

Is there anyway to automatically adjust the width of the hostname label area based on the maximum length of the hostname within each matrix?

**Comment by arlake228** [comment]
I agree that it should do a better job of automatically calculating this but there is a workaround as an FYI. In /opt/maddash/maddash-webui/etc/config.json you can set the *textBlockSize* for a specific grid as discussed here http://software.es.net/maddash/config_webui.html#grids-properties.

There is an example here too (and is likely in your version on disk): https://raw.githubusercontent.com/esnet/maddash/master/maddash-webui/web/etc/config.json

**Comment by soichih** [comment]
Thanks. Does this configuration applies to *all* dashboards? Or is the "OWAMP" the name of a specific dashboard (or maybe called "grid")? Also, do I need to restart maddash-server (or httpd?) to apply this config?

**Comment by arlake228** [comment]
The example in the file only applies to the grid named OWAMP. You do not need to restart maddash, but you may need to clear your browser cache.
