### ISSUE TITLE
generate_gui_configuration uninformative message

### ISSUE THREAD

**Issue by igarny** [esnet/maddash#36]
Dear Andy,

Please look at the error message below:

[root@pertcs01 ~]# vi /var/www/html/trainmesh.json
[root@pertcs01 ~]# /usr/lib/perfsonar/bin/generate_gui_configuration
2016/10/14 09:41:59 (28188) ERROR> GUIAgent.pm:285 perfSONAR_PS::MeshConfig::GUIAgent::__generate_maddash_config - Problem generating maddash configuration: YAML Error: Stream does not end with newline character
   Code: YAML_PARSE_ERR_NO_FINAL_NEWLINE
   Line: 0
   Document: 0
 at /usr/share/perl5/YAML.pm line 36
2016/10/14 09:41:59 (28188) ERROR> GUIAgent.pm:231 perfSONAR_PS::MeshConfig::GUIAgent::__configure_guis - Problem generating maddash configuration: Problem generating maddash configuration: YAML Error: Stream does not end with newline character
   Code: YAML_PARSE_ERR_NO_FINAL_NEWLINE
   Line: 0
   Document: 0
 at /usr/share/perl5/YAML.pm line 36

I am applying also a cat of the meshconf. The stated error though does not fit to the structure of the file. 

[trainmesh.txt](https://github.com/esnet/maddash/files/529280/trainmesh.txt)

The meshconfig was of course generated by /usr/lib/perfsonar/bin/build_json without the new line in the end (I have added it with vim). The meshconfig is already successfully applied at a pS toolkit instance.

Regards,
Ivan

**Comment by igarny** [comment]
[root@pertcs01 ~]# yum list installed maddash-server
Loaded plugins: fastestmirror, presto
Loading mirror speeds from cached hostfile
 * Internet2: mirror.in2p3.fr
 * base: linuxsoft.cern.ch
 * epel: fr2.rpmfind.net
 * extras: linuxsoft.cern.ch
 * updates: linuxsoft.cern.ch
Installed Packages
maddash-server.noarch                                                                 2.0-0.9rc1.el6                                                                  @Internet2-staging

**Comment by arlake228** [comment]
What happens if you manually enter a newline at the very end of your /etc/maddash/maddash-server/maddash.yaml file and try again? That seems to be what the error indicates is the problem and YAML is very picky about whitespace. If that doesn't work can you send me your /etc/maddash/maddash-server/maddash.yaml?

**Comment by igarny** [comment]
Ohhh. I really thought it is the input files. I have checked the meshcofig and the /etc/perfsonar/meshconfig-guiagent.conf. Isn't maddash.yaml only the result of the /usr/lib/perfsonar/bin/generate_gui_configuration command?

The maddash.yaml file was as by the default example.

I have added a new line at the end of the demo file and got a different error. Will explore further.

**Comment by arlake228** [comment]
old meshconfig issue (not maddash) closing.
