### ISSUE TITLE
Error loading data

### ISSUE THREAD

**Issue by ryanhitch** [esnet/maddash#51]
On a clean install of perfsonar-centralmanagement on Centos 7.3 our users are experiencing issues viewing graphs using any browser but Chrome. We had no issues with out previous perfSONAR 3.5 central management mad-dash installation. Any suggestions for troubleshooting?

Chrome: graphs load properly
Firefox: blank where graphs should be
Edge: "Error loading data Error retreiving data An unknown error occured" is displayed where graphs should be
IE 11: blank where graphs should be

**Comment by arlake228** [comment]
Confirmed to be a mixture of http and https

**Comment by dimm0** [comment]
How do you fix the mixture of http and https? Is it configurable?
